spring.application.name=LocalEventFinder

spring.datasource.url=jdbc:postgresql://localhost:5432/event_finder
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
